# Homepage
lbf_admin_homepage:
    path:     /
    defaults: { _controller: LBFAdminBundle:Admin:index }

# Answer to an order
lbf_admin_currentOrders:
    path:     /currentOrders
    defaults: { _controller: LBFAdminBundle:Admin:currentOrders }

lbf_admin_answer:
    path:     /answer/{orderId}
    defaults: { _controller: LBFAdminBundle:Admin:answerOrder }
    requirements:
        orderId: \d+

lbf_admin_delete:
    path:     /delete/{orderId}
    defaults: { _controller: LBFAdminBundle:Admin:deleteOrder }
    requirements:
        orderId: \d+

lbf_admin_complete:
    path:     /complete/{orderId}
    defaults: { _controller: LBFAdminBundle:Admin:completeOrder }
    requirements:
        orderId: \d+

lbf_admin_pastOrders:
    path:     /pastOrders
    defaults: { _controller: LBFAdminBundle:Admin:pastOrders }


# Check about users
lbf_admin_users:
    path:     /users
    defaults: { _controller: LBFAdminBundle:Admin:users }

lbf_admin_newsletter:
    path:     /newsletterEmails
    defaults: { _controller: LBFAdminBundle:Admin:newsletter }

lbf_admin_newsletterEmails:
    path:     /newsletterEmails/emails
    defaults: { _controller: LBFAdminBundle:Admin:newsletterEmails }

lbf_admin_newsletterEmailsSpe:
    path:     /newsletterEmails/emails/{emailType}
    defaults: { _controller: LBFAdminBundle:Admin:newsletterEmails }

lbf_admin_edit_email:
    path:     /newsletterEmails/edit/{emailId}
    defaults: { _controller: LBFAdminBundle:Admin:editEmail }
    requirements:
        emailId: \d+

lbf_admin_delete_email:
    path:     /newsletterEmails/delete/{emailId}
    defaults: { _controller: LBFAdminBundle:Admin:deleteEmail }
    requirements:
        emailId: \d+

lbf_admin_comments:
    path:     /comments
    defaults: { _controller: LBFAdminBundle:Admin:comments }

lbf_admin_comments_sorted:
    path:     /comments/sortedBy/{sortBy}/{order}
    defaults: { _controller: LBFAdminBundle:Admin:comments }

lbf_admin_new_comment:
    path:     /comments/new
    defaults: { _controller: LBFAdminBundle:Admin:newComment }

lbf_admin_edit_comment:
    path:     /comments/edit/{commentId}
    defaults: { _controller: LBFAdminBundle:Admin:newComment }
    requirements:
        commentId: \d+

lbf_admin_delete_comment:
    path:     /comments/delete/{commentId}
    defaults: { _controller: LBFAdminBundle:Admin:deleteComment }
    requirements:
        commentId: \d+


# Change elements
lbf_admin_elements:
    path:     /elements
    defaults: { _controller: LBFAdminBundle:Admin:elements }

lbf_admin_new_element:
    path:     /elements/new
    defaults: { _controller: LBFAdminBundle:Admin:newElement }

lbf_admin_edit_element:
    path:     /elements/edit/{elementId}
    defaults: { _controller: LBFAdminBundle:Admin:newElement }
    requirements:
        elementId: \d+

lbf_admin_delete_element:
    path:     /elements/delete/{elementId}
    defaults: { _controller: LBFAdminBundle:Admin:deleteElement }
    requirements:
        elementId: \d+


# Change recipes
lbf_admin_recipes:
    path:     /recipes
    defaults: { _controller: LBFAdminBundle:Admin:recipes }

lbf_admin_new_recipe:
    path:     /recipes/new
    defaults: { _controller: LBFAdminBundle:Admin:newRecipe }

lbf_admin_edit_recipe:
    path:     /recipes/edit/{recipeId}
    defaults: { _controller: LBFAdminBundle:Admin:newRecipe }
    requirements:
        recipeId: \d+

lbf_admin_delete_recipe:
    path:     /recipes/delete/{recipeId}
    defaults: { _controller: LBFAdminBundle:Admin:deleteRecipe }
    requirements:
        recipeId: \d+