lbf_admin_homepage:
    path:     /
    defaults: { _controller: LBFAdminBundle:Admin:index }

lbf_admin_answer:
    path:     /answer/{orderId}
    defaults: { _controller: LBFAdminBundle:Admin:answer }
    requirements:
        orderId: \d+

lbf_admin_delete:
    path:     /delete/{orderId}
    defaults: { _controller: LBFAdminBundle:Admin:delete }
    requirements:
        orderId: \d+

lbf_admin_complete:
    path:     /complete/{orderId}
    defaults: { _controller: LBFAdminBundle:Admin:complete }
    requirements:
        orderId: \d+

lbf_admin_newsletterEmails:
    path:     /newsletterEmails
    defaults: { _controller: LBFAdminBundle:Admin:newsletterEmails }