# Homepage
lbf_admin_homepage:
    path:     /
    defaults: { _controller: LBFAdminBundle:Admin:index }

# Answer to an order
lbf_admin_currentOrders:
    path:     /currentOrders/
    defaults: { _controller: LBFAdminBundle:Admin:currentOrders }

lbf_admin_currentOrders_sorted:
    path:     /currentOrders/sortedBy/{sortBy}/{order}/
    defaults: { _controller: LBFAdminBundle:Admin:currentOrders }

lbf_admin_answer:
    path:     /answer/{orderId}/
    defaults: { _controller: LBFAdminBundle:Admin:answerOrder }
    requirements:
        orderId: \d+

lbf_admin_delete:
    path:     /delete/{orderId}/
    defaults: { _controller: LBFAdminBundle:Admin:deleteOrder }
    requirements:
        orderId: \d+

lbf_admin_delete_complete:
    path:     /delete/complete/{orderId}/
    defaults: { _controller: LBFAdminBundle:Admin:deleteOrderComplete }
    requirements:
        orderId: \d+

lbf_admin_complete:
    path:     /complete/{orderId}/
    defaults: { _controller: LBFAdminBundle:Admin:completeOrder }
    requirements:
        orderId: \d+

lbf_admin_pastOrders:
    path:     /pastOrders/
    defaults: { _controller: LBFAdminBundle:Admin:pastOrders }


# Check about users
lbf_admin_users:
    path:     /users/
    defaults: { _controller: LBFAdminBundle:Admin:users }

lbf_admin_users_sorted:
    path:     /users/sortedBy/{sortBy}/{order}/
    defaults: { _controller: LBFAdminBundle:Admin:users }

lbf_admin_edit_user:
    path:     /users/edit/{userId}/
    defaults: { _controller: LBFAdminBundle:Admin:newUser }
    requirements:
        userId: \d+

lbf_admin_delete_user:
    path:     /users/delete/{userId}/
    defaults: { _controller: LBFAdminBundle:Admin:deleteUser }
    requirements:
        userId: \d+

lbf_admin_usersEmails:
    path:     /users/allEmails/
    defaults: { _controller: LBFAdminBundle:Admin:usersEmails }

lbf_admin_companies:
    path:     /companies/
    defaults: { _controller: LBFAdminBundle:Admin:companies }

lbf_admin_companies_sorted:
    path:     /companies/sortedBy/{sortBy}/{order}/
    defaults: { _controller: LBFAdminBundle:Admin:companies }

lbf_admin_edit_company:
    path:     /companies/edit/{companyId}/
    defaults: { _controller: LBFAdminBundle:Admin:newCompany }
    requirements:
        companyId: \d+

lbf_admin_delete_company:
    path:     /companys/delete/{companyId}/
    defaults: { _controller: LBFAdminBundle:Admin:deleteCompany }
    requirements:
        companyId: \d+

lbf_admin_companiesEmails:
    path:     /companies/allEmails/
    defaults: { _controller: LBFAdminBundle:Admin:companiesEmails }


# Check about newsletters
lbf_admin_newsletter:
    path:     /newsletterEmails/
    defaults: { _controller: LBFAdminBundle:Admin:newsletter }

lbf_admin_emails_sorted:
    path:     /newsletterEmails/sortedBy/{sortBy}/{order}/
    defaults: { _controller: LBFAdminBundle:Admin:newsletter }

lbf_admin_newsletterEmails:
    path:     /newsletterEmails/emails/
    defaults: { _controller: LBFAdminBundle:Admin:newsletterEmails }

lbf_admin_newsletterEmailsSpe:
    path:     /newsletterEmails/emails/{emailType}/
    defaults: { _controller: LBFAdminBundle:Admin:newsletterEmails }

lbf_admin_edit_email:
    path:     /newsletterEmails/edit/{emailId}/
    defaults: { _controller: LBFAdminBundle:Admin:editEmail }
    requirements:
        emailId: \d+

lbf_admin_delete_email:
    path:     /newsletterEmails/delete/{emailId}/
    defaults: { _controller: LBFAdminBundle:Admin:deleteEmail }
    requirements:
        emailId: \d+


# Check about comments
lbf_admin_comments:
    path:     /comments/
    defaults: { _controller: LBFAdminBundle:Admin:comments }

lbf_admin_comments_sorted:
    path:     /comments/sortedBy/{sortBy}/{order}/
    defaults: { _controller: LBFAdminBundle:Admin:comments }

lbf_admin_new_comment:
    path:     /comments/new/
    defaults: { _controller: LBFAdminBundle:Admin:newComment }

lbf_admin_edit_comment:
    path:     /comments/edit/{commentId}/
    defaults: { _controller: LBFAdminBundle:Admin:newComment }
    requirements:
        commentId: \d+

lbf_admin_delete_comment:
    path:     /comments/delete/{commentId}/
    defaults: { _controller: LBFAdminBundle:Admin:deleteComment }
    requirements:
        commentId: \d+


# Change elements
lbf_admin_elements:
    path:     /elements/
    defaults: { _controller: LBFAdminBundle:Admin:elements }

lbf_admin_elements_sorted:
    path:     /elements/sortedBy/{sortBy}/{order}/
    defaults: { _controller: LBFAdminBundle:Admin:elements }

lbf_admin_new_element:
    path:     /elements/new/
    defaults: { _controller: LBFAdminBundle:Admin:newElement }

lbf_admin_edit_element:
    path:     /elements/edit/{elementId}/
    defaults: { _controller: LBFAdminBundle:Admin:newElement }
    requirements:
        elementId: \d+

lbf_admin_delete_element:
    path:     /elements/delete/{elementId}/
    defaults: { _controller: LBFAdminBundle:Admin:deleteElement }
    requirements:
        elementId: \d+


# Change recipes
lbf_admin_recipes:
    path:     /recipes/
    defaults: { _controller: LBFAdminBundle:Admin:recipes }

lbf_admin_recipes_sorted:
    path:     /recipes/sortedBy/{sortBy}/{order}/
    defaults: { _controller: LBFAdminBundle:Admin:recipes }

lbf_admin_new_recipe:
    path:     /recipes/new/
    defaults: { _controller: LBFAdminBundle:Admin:newRecipe }

lbf_admin_edit_recipe:
    path:     /recipes/edit/{recipeId}/
    defaults: { _controller: LBFAdminBundle:Admin:newRecipe }
    requirements:
        recipeId: \d+

lbf_admin_delete_recipe:
    path:     /recipes/delete/{recipeId}/
    defaults: { _controller: LBFAdminBundle:Admin:deleteRecipe }
    requirements:
        recipeId: \d+


# Pages
lbf_admin_pages:
    path:     /pages/
    defaults: { _controller: LBFAdminBundle:Admin:pages }

lbf_admin_pages_asked:
    path:     /pages/asked/{pageId}/
    defaults: { _controller: LBFAdminBundle:Admin:pages }
    requirements:
        pageId: \d+

lbf_admin_new_page:
    path:     /pages/new/
    defaults: { _controller: LBFAdminBundle:Admin:newPage }

lbf_admin_edit_page:
    path:     /pages/edit/{pageId}/
    defaults: { _controller: LBFAdminBundle:Admin:newPage }
    requirements:
        pageId: \d+

lbf_admin_delete_page:
    path:     /pages/delete/{pageId}/
    defaults: { _controller: LBFAdminBundle:Admin:deletePage }
    requirements:
        pageId: \d+

# Members
lbf_admin_members:
    path:     /members/
    defaults: { _controller: LBFAdminBundle:Admin:members }

lbf_admin_members_sorted:
    path:     /members/sortedBy/{sortBy}/{order}/
    defaults: { _controller: LBFAdminBundle:Admin:members }

lbf_admin_new_member:
    path:     /members/new/
    defaults: { _controller: LBFAdminBundle:Admin:newMember }

lbf_admin_edit_member:
    path:     /members/edit/{memberId}/
    defaults: { _controller: LBFAdminBundle:Admin:newMember }
    requirements:
        memberId: \d+

lbf_admin_delete_member:
    path:     /members/delete/{memberId}/
    defaults: { _controller: LBFAdminBundle:Admin:deleteMember }
    requirements:
        memberId: \d+

# Photos
lbf_admin_photos:
    path:     /photos/
    defaults: { _controller: LBFAdminBundle:Admin:photos }

lbf_admin_photos_sorted:
    path:     /photos/sortedBy/{sortBy}/{order}/
    defaults: { _controller: LBFAdminBundle:Admin:photos }

lbf_admin_new_photo:
    path:     /photos/new/
    defaults: { _controller: LBFAdminBundle:Admin:newPhoto }

lbf_admin_edit_photo:
    path:     /photos/edit/{photoId}/
    defaults: { _controller: LBFAdminBundle:Admin:newPhoto }
    requirements:
        photoId: \d+

lbf_admin_delete_photo:
    path:     /photos/delete/{photoId}/
    defaults: { _controller: LBFAdminBundle:Admin:deletePhoto }
    requirements:
        photoId: \d+



