<?php

namespace LBF\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementRepository extends EntityRepository
{
	public function findAllSortedByCategory	()
	{
		return $this->createQueryBuilder('e')
					->orderBy('e.category', 'ASC')
					->getQuery()
					->getResult();
	}
}
