<?php

namespace LBF\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HomePhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomePhotoRepository extends EntityRepository
{
}
