<?php

namespace LBF\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TestimonyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestimonyRepository extends EntityRepository
{
	public function findSortedByType($sortType, $order) {
		return $this->createQueryBuilder('t')
					->orderBy('t.parameter = :parameter', $order)
						->setParameter('parameter', $sortType)
					->getQuery()
					->getResult();
	}
}
