lbf_main_homepage:
    path:     /
    defaults: { _controller: LBFMainBundle:Main:index }

lbf_main_add_to_cart:
    path:     /addToCart/{type}/{quantity}
    defaults: { _controller: LBFMainBundle:Main:addToCart }
    requirements:
        quantity: \d*

lbf_main_empty_cart:
    path:     /emptyCart
    defaults: { _controller: LBFMainBundle:Main:emptyCart }