<?php

namespace LBF\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends EntityRepository
{
	public function findSpecific ($user, $status, $qty)
	{
		return $this->createQueryBuilder('o')
					->where ('o.user = :user')
						->setParameter('user', $user)
					->andWhere ('o.status = :status')
						->setParameter('status', $status)
					->orderBy('o.createdAt', 'DESC')
					->setMaxResults($qty)
					->getQuery()
					->getResult();
	}

	public function findSpecificNon ($user, $status, $qty)
	{
		return $this->createQueryBuilder('o')
					->where ('o.user = :user')
						->setParameter('user', $user)
					->andWhere ('o.status != :status')
						->setParameter('status', $status)
					->orderBy('o.createdAt', 'DESC')
					->setMaxResults($qty)
					->getQuery()
					->getResult();
	}

	public function findSpecificAdmin ($status, $qty)
	{
		return $this->createQueryBuilder('o')
					->where ('o.status = :status')
						->setParameter('status', $status)
					->orderBy('o.createdAt', 'DESC')
					->setMaxResults($qty)
					->getQuery()
					->getResult();
	}

	public function findSpecificAdminNon ($status, $qty)
	{
		return $this->createQueryBuilder('o')
					->where ('o.status != :status')
						->setParameter('status', $status)
					->orderBy('o.createdAt', 'DESC')
					->setMaxResults($qty)
					->getQuery()
					->getResult();
	}

	

}
